// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLMWZJEi1XQW7MnIPydGMWd7-hmvSslM',
    appId: '1:585591392320:web:dd9cc56305db83022077a5',
    messagingSenderId: '585591392320',
    projectId: 'mardenhub',
    authDomain: 'mardenhub.firebaseapp.com',
    storageBucket: 'mardenhub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6kkqvkgon4_bmlS4lg_d2pC2qIRT9vwE',
    appId: '1:585591392320:android:ac00e5737744add32077a5',
    messagingSenderId: '585591392320',
    projectId: 'mardenhub',
    storageBucket: 'mardenhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArda-cLTtEkEMYijfHwmQJIm6hcIcwexY',
    appId: '1:585591392320:ios:6490c955b0c7c9b12077a5',
    messagingSenderId: '585591392320',
    projectId: 'mardenhub',
    storageBucket: 'mardenhub.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectLaundry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArda-cLTtEkEMYijfHwmQJIm6hcIcwexY',
    appId: '1:585591392320:ios:6490c955b0c7c9b12077a5',
    messagingSenderId: '585591392320',
    projectId: 'mardenhub',
    storageBucket: 'mardenhub.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectLaundry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLMWZJEi1XQW7MnIPydGMWd7-hmvSslM',
    appId: '1:585591392320:web:064cd78755e9310f2077a5',
    messagingSenderId: '585591392320',
    projectId: 'mardenhub',
    authDomain: 'mardenhub.firebaseapp.com',
    storageBucket: 'mardenhub.firebasestorage.app',
  );
}
